name: frontend
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies:
  flutter_carousel_slider: ^1.1.0
  flutter_image_slideshow: ^0.1.5
  supabase: ^1.8.1
  font_awesome_flutter: ^10.4.0
  
  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.0.0
  get_storage: ^2.1.1
  bottom_navy_bar: ^6.0.0
  multiselect: ^0.1.0
  image_picker: ^0.8.9
  dotted_border: ^2.0.0+3
  smooth_page_indicator: ^1.1.0
  rive: ^0.7.16
  syncfusion_flutter_datepicker: ^22.1.34
  
  

dev_dependencies:
  supabase: ^1.8.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_image_slideshow: ^0.1.5

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/animations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Black.ttf
        - asset: fonts/Tajawal-Bold.ttf
        - asset: fonts/Tajawal-ExtraBold.ttf
        - asset: fonts/Tajawal-ExtraLight.ttf
        - asset: fonts/Tajawal-Light.ttf
        - asset: fonts/Tajawal-Medium.ttf
        - asset: fonts/Tajawal-Regular.ttf
